### ISSUE TITLE
Chore: Complete the `questions` array in `data.js`

### ISSUE THREAD

**Issue by imtiaz101325** [imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break#12]
in `src/data.js` we currently do not have all the question data. Use the questions data in #9 to manually complete the `questions` array with data.

**Comment by M-Hajjar** [comment]
Done.
I have added 7 Random questions about  coffee and coffee breaks 
the subject of the questions is easy to change so feel free to reach out if you don't like it 
but for now, we can use these questions as a resource for the app.

**Comment by M-Hajjar** [comment]
this issue is done 
as the team decided we add 10 questions manuly 
and it has been pushed to main branch through PR "add js files #28"
