### ISSUE TITLE
Hello this is a screenshot to show QuestionCounter working good

### ISSUE THREAD

**Issue by YousraElmag** [imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break#21]
![Screenshot 2024-05-28 10 32 26 AM](https://github.com/imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break/assets/165666429/ff7d459a-cac6-4efb-9441-b3a1293fd93c)
![Screenshot 2024-05-28 10 32 38 AM](https://github.com/imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break/assets/165666429/dbcd130e-6782-4b24-9b25-c68686c79e43)
![Screenshot 2024-05-28 10 32 44 AM](https://github.com/imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break/assets/165666429/245679d0-c5fd-432e-9379-0fdd33d709a0)

**Comment by M-Hajjar** [comment]
the team has decided on a design for the app
so this one won't be needed  
and it has been pushed to main branch through PR "add js files https://github.com/imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break/pull/28"
