### ISSUE TITLE
Change `title` in `index.html`

### ISSUE THREAD

**Issue by imtiaz101325** [imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break#3]
In `index.html` the `title` is a generic one. We need to change it to something meaningful.

**Comment by M-Hajjar** [comment]
I have changed the Title to " Coffee Break Quiz " on "Hajjar" branch 
let me know if you all agree before I merch and close this issue

**Comment by imtiaz101325** [comment]
@M-Hajjar please always make separate branches for different issues. Also please make a PR so that we can see your changes.
