### ISSUE TITLE
Fork This project

### ISSUE THREAD

**Issue by M-Hajjar** [imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break#35]
as our mentor Imtiaz Requested 
everyone who is working on this project should Fork it and then clone it 
after that, we will see how to deploy it

**Comment by azizsigar** [comment]
forked 

https://github.com/azizsigar/coffie-break-quiz

**Comment by M-Hajjar** [comment]
done 
https://github.com/M-Hajjar/hyf-c48-w2-browsers-quiz-app-coffee-break

**Comment by M-Hajjar** [comment]
done
