### ISSUE TITLE
Buge :  a user see a blank page after restart the quiz 

### ISSUE THREAD

**Issue by M-Hajjar** [imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break#38]
when a user finishes the quiz and clicks " go home " to restart the quiz 
a blank page shows up 
![Screenshot (22)](https://github.com/imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break/assets/69475046/d57b7a22-b6cf-41ed-9d95-7faa9ede77f6)
as Imtiaz explained to me it has something to do in qustionPage.js 
the function needs to know where to go next after its been clicked  
![d5be65ce-4784-4618-be4a-58e9cfa52935](https://github.com/imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break/assets/69475046/c9e22d50-42ef-4f07-8a7c-40ad0e8e5745)

**Comment by azizsigar** [comment]
`[fixedRestartBtn](url)` branch is oke. i fixed already yesterday

**Comment by M-Hajjar** [comment]
however in this branch [fixedRestartBtn]
 we have a different bug now 
as i understand the score now saves the correct answers
even after refreshing the page
but it saves it forever ( even after the quiz is done )
![Screenshot (23)](https://github.com/imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break/assets/69475046/ee9a9644-deec-4e6c-8011-a25bed1999b9)
