### ISSUE TITLE
new Style suggested 

### ISSUE THREAD

**Issue by M-Hajjar** [imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break#39]
a new style suggested by Yousra 

is it completed? 
do we need to add anything before we merge it?
does it change the main functionality of the app?

**Comment by YousraElmag** [comment]
we need to add code to change the background colour for correct answer to green or red if false

**Comment by M-Hajjar** [comment]
yeah im dealing with that on issue #37
