### ISSUE TITLE
Add a favicon to the project

### ISSUE THREAD

**Issue by imtiaz101325** [imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break#4]
Our project needs a [favicon](https://en.wikipedia.org/wiki/Favicon) for it to look good. Please add one.

**Comment by M-Hajjar** [comment]
I have added a coffee favicon on "Hajjar" branch
let me know if you all agree before I merch and close this issue

**Comment by imtiaz101325** [comment]
@M-Hajjar please always make separate branches for different issues. Also please make a PR so that we can see your changes.
