### ISSUE TITLE
Create a User Interface

### ISSUE THREAD

**Issue by M-Hajjar** [imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break#6]
Create a User Interface that contains : 
*background image or nice color
*Create a nice cart in the middle that will 1 question at a time 
*the cart should have a place for the question on the top,  4 possible answers, and a "continue" button

**Comment by M-Hajjar** [comment]
I have created a simple UI that covers the basic requirements 
it can be updated if we have enough time after finishing the "Must-have"
you may view it in the branch "**Create-user-interface**"
let me know if you all agree before I merch and close this issue

**Comment by azizsigar** [comment]
nice

**Comment by azizsigar** [comment]
Nice
