### ISSUE TITLE
questions with answers 

### ISSUE THREAD

**Issue by YousraElmag** [imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break#9]
hello ,I found this Json file have a lot of questions with answers I suggest used it and make the questions randomly
https://gist.github.com/cmota/f7919cd962a061126effb2d7118bec72

**Comment by M-Hajjar** [comment]
Nice we use this as a resource for questions  ( 7 questions each time is enough I think )
we have to make it using js I believe 
if anyone on this please assign yourself

**Comment by YousraElmag** [comment]
I can do that after meeting today

**Comment by imtiaz101325** [comment]
The team decided to:
For now use a few of these to make up 10 questions in total.
In the future if we have time we can map these in to make random questions as a feature.

**Comment by M-Hajjar** [comment]
no need to it
